### PR TITLE
[Fix] Wraped VueDisqus in no-ssr component

### LINKED ISSUE #19: hook error
current master f209b9d44b54645474703d411d2dbd9122149b86
```
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'title' of undefined"

found in

---> <Anonymous>
       <Nuxt>
         <Anonymous>
           <Root>
```
To reproduce
npm build 
npm start

### PR DESCRIPTION
**Pull request by yashha**
And fixed so server client markup mismatch
Closes #19

### CODE REVIEW

**Comment by yashha** [comment]
I changed 2 lines?

**Comment by yashha** [comment]
DOS Format?
Are the files in DOS Format?
```
File Name to Write [DOS Format]: pages/_article.vue
```

**Comment by krestaino** [comment]
This one also conflicts with #18. Just curious if it was intentional to remove the component `FeaturedImage.vue` from `_article.vue`?

**Comment by krestaino** [comment]
I wasn't aware of `<no-ssr>`, thanks!

**Pull request merged**
